# Generated by Django 5.1.1 on 2024-09-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordhistory',
            name='old_passwords',
            field=models.CharField(max_length=255),
        ),
    ]
