# Generated by Django 5.1 on 2024-09-06 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_passworditem_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('groupId', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=100)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.passworditem')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
