# Generated by Django 5.1.1 on 2024-09-06 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='itemId',
            field=models.ForeignKey(db_column='itemId', on_delete=django.db.models.deletion.CASCADE, to='api.passworditem'),
        ),
    ]
